### PR TITLE
Fix for inconsistent behavior with System Path and error while running dameon as service 

### PR DESCRIPTION
**Pull request by ayushbhatt29**
Signed-off-by: ayushbhatt29 <abhatt@msystechnologies.com>
#273 
Addressing the issue of task getting failed when using Set-AzVMExtension to change the "daemon" setting from "service" to "task".

### CODE REVIEW

**Comment by ayushbhatt29** [comment]
When daemon settings of a windows node are changed from **service** to **task** by running  `az vm extension set` command twice, the scheduled task of chef-client fails with action `cmd /c "ruby chef-client -L C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.13.1.1/chef-client.log -c C:/chef/client.rb"` and can be seen in task scheduler as given below.
Screenshot (4)


After applying the fix the task runs successfully with action - `/c "C:/opscode/chef/embedded/bin/ruby.exe C:/opscode/chef/bin/chef-client -L C:/chef/chef-client.log -c C:/chef/client.rb"`
Screenshot (5)

**Comment by ayushbhatt29** [comment]
**The parts this PR Handles are as follows -**

- It resolves the issue of shifting from daemon setting **service** to daemon setting **task** in windows node  where **scheduled task**  fails with action `cmd /c "ruby chef-client -L C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.13.1.1/chef-client.log -c C:/chef/client.rb"` and also the error of `FATAL: Windows Chef Infra Client interval runs are not supported in Chef Infra Client 15 and later` when shifting from  daemon setting **task** to daemon setting **service**  , now changing daemon setting from shell will no longer raise error.

- It also covers the issue of both daemon setting **service** and **task** running simultaneously, so now other daemon setting is stopped before new one is set.

- It resolves the error of interval runs that is no longer supported by chef-client, so setting `chef_daemon_interval` for daemon setting service for windows vm will not set interval run in client.rb file and will not raise `FATAL: Windows Chef Infra Client interval runs are not supported in Chef Infra Client 15 and later.`

**Review by dheerajd-msys — APPROVED** [review]
Looks good!

**Review by NAshwini — APPROVED** [review]
LGTM. Thanks @ayushbhatt29.

**Review by Vasu1105 — APPROVED** [review]
Thanks @ayushbhatt29

**Pull request merged**
